prompt = """You are an expert in scientometrics and academic taxonomy construction.
Your task is to merge and refine several existing hierarchical research taxonomies (generated by different LLMs) into a single, unified, and well-structured taxonomy.

Each input taxonomy may have different levels of depth, naming conventions, or coverage.
Your goal is to produce the most complete, logically organized, and non-redundant taxonomy possible.

Input:
You will receive multiple taxonomies in JSON or hierarchical text format.

Your Responsibilities:

Merge all unique nodes and subfields from the input taxonomies into one unified structure.

Preserve the deepest available details (prefer more detailed subfields over general ones).

Eliminate duplicates or near-duplicates (e.g., merge "AI" and "Artificial Intelligence").

Ensure consistency in hierarchy and naming:

Use singular nouns (e.g., "System" not "Systems").

Use "and" instead of "&".

Capitalize consistently across all levels.

Assign each sub-area to only one parent domain — no overlapping or ambiguous placement.

Unify terminology (e.g., "Data Mining" and "Knowledge Discovery" → keep the standard term or merge as "Data Mining and Knowledge Discovery").

Keep hierarchical relationships coherent — maintain broad → sub-area → sub-sub-area depth.

Retain field codes (if available) from OECD/UNESCO, or infer them if clear.

When merging conflicts arise, choose the more descriptive or standard version.

Output Format:
Provide the final unified taxonomy in well-formatted JSON, preserving all hierarchical relationships.

Example format:
{
  "Natural Sciences": {
    "Mathematics (1.01)": {
      "Applied Mathematics": ["Numerical Analysis", "Optimization"],
      "Statistics": ["Bayesian Methods", "Data Analysis"]
    },
    "Computer and Information Sciences (1.02)": {
      "Artificial Intelligence": {
        "Machine Learning": ["Supervised Learning", "Reinforcement Learning"],
        "Natural Language Processing": ["Text Summarization", "Information Extraction"]
      }
    }
  }
}

Final Requirements:

Output a single, logically coherent taxonomy with maximum depth and coverage.

No redundant or duplicated nodes.

Compact yet comprehensive, suitable for automated classification of research abstracts.

The taxonomy must be based on the deepest available details from all provided sources."""
